version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_nosql
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./doc_files:/data/import
    environment:
      MONGO_INITDB_DATABASE: reto_nosql

volumes:
  mongo_data:
